export { CheckpointManager, type CheckpointManagerOptions, type CheckpointRuntimePolicy, createCheckpointManager, ensureCheckpointSchema, resolveCheckpointPolicy, } from './checkpoints/index.js';
export { AuditLogger } from './context-graph/audit/AuditLogger.js';
export { EvidenceGate } from './context-graph/evidence/EvidenceGate.js';
export { ABACEngine } from './context-graph/security/ABACEngine.js';
export type { DeleteMemoryInput, DeleteMemoryResult, GetMemoryInput, GetMemoryResult, HealthStatus, MemoryProvider, SearchMemoryInput, SearchMemoryResult, StoreMemoryInput, StoreMemoryResult, } from './provider/MemoryProvider.js';
export { LocalMemoryProvider } from './providers/LocalMemoryProvider.js';
export { RemoteMemoryProvider } from './providers/RemoteMemoryProvider.js';
export { createGraphRAGIngestService, type GraphRAGIngestRequest, type GraphRAGIngestResult, GraphRAGIngestService, } from './services/GraphRAGIngestService.js';
export { createGraphRAGService, type GraphRAGQueryRequest, type GraphRAGResult, GraphRAGService, type GraphRAGServiceConfig, } from './services/GraphRAGService.js';
export type { CheckpointBranchRequest, CheckpointBranchResult, CheckpointConfig, CheckpointContext, CheckpointListPage, CheckpointSnapshot, Memory, MemoryAnalysisResult, MemoryCoreConfig, MemoryGraph, MemoryMetadata, MemoryProviderError, MemoryRelationship, MemorySearchResult, MemoryStats, QdrantConfig, RelationshipType, } from './types.js';
import { LocalMemoryProvider } from './providers/LocalMemoryProvider.js';
import { RemoteMemoryProvider } from './providers/RemoteMemoryProvider.js';
export declare function createMemoryProviderFromEnv(): LocalMemoryProvider | RemoteMemoryProvider;
