[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cortex-connectors"
version = "0.1.0"
description = "Manifest-driven connectors runtime for Cortex-OS"
authors = [{name = "brAInwav Development Team", email = "ops@brainwav.ai"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.110",
    "uvicorn[standard]>=0.23",
    "pydantic>=2.5",
    "httpx>=0.27",
    "structlog>=24.1",
    "prometheus-client>=0.19",
    "instructor>=1.2",
    "opentelemetry-sdk>=1.21",
    "opentelemetry-exporter-otlp>=1.21",
]

[project.optional-dependencies]
test = [
    "pytest>=8.0",
    "pytest-asyncio>=0.23",
    "pytest-cov>=4.1",
]

[project.scripts]
cortex-connectors = "cortex_connectors.cli:main"
cortex-connectors-server = "cortex_connectors.server:main"

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "--strict-markers"
