export function useSettingsStore() {
	return {
		general: {
			theme: 'dark',
			language: 'en',
			fontSize: 'base',
			defaultModel: '',
			defaultPrompt: '',
			autoScrollOutput: true,
			enterToSubmit: true,
			doubleEnterToSubmit: false,
			showUsernameInChat: true,
			showModelNameInChat: true,
		},
		notifications: {
			webhook_url: '',
		},
		interface: {
			sidebarVisible: true,
			sidebarWidth: 260,
			chatLayout: 'standard',
			messageAlignment: 'left',
			showTimestamps: true,
			showScrollToBottom: true,
			showModelIcon: true,
			showUserIcon: true,
			enableSyntaxHighlighting: true,
			enableCodeCopyButton: true,
			enableCodeExecution: true,
			enableWebSearch: true,
			enableFileUpload: true,
			enableVoiceInput: true,
			enableEmojiPicker: true,
			enableMarkdownRendering: true,
			enableLaTeXRendering: true,
			enableCodeBlockLineNumbers: true,
		},
		personalization: {
			customInstructions: '',
			persona: 'default',
			responseStyle: 'concise',
			creativityLevel: 50,
			detailLevel: 50,
			tonePreference: 'neutral',
			communicationStyle: 'professional',
			preferredTopics: [],
			blockedTopics: [],
			enablePersonalization: true,
		},
		advanced: {
			enableCommunitySharing: false,
			hideSuggestedPrompts: false,
			playgroundEnabled: false,
			archiveChats: false,
			featureFlags: {
				audio: false,
				webSearch: false,
				images: false,
				codeExecution: false,
			},
		},
		chats: {
			autoTitleChat: true,
			recentChatCount: 5,
			chatDirection: 'ltr',
			chatSpacing: 'compact',
			showCodeByDefault: false,
			continuousChat: false,
			exportFormat: 'pdf',
			autoSaveChat: true,
			chatHistoryLimit: 30,
		},
		connections: {
			openaiApiKey: '',
			anthropicApiKey: '',
			googleApiKey: '',
			mistralApiKey: '',
			groqApiKey: '',
			openRouterApiKey: '',
			customOpenaiEndpoint: '',
			customOpenaiApiKey: '',
		},
		audio: {
			ttsEnabled: false,
			ttsEngine: 'browser',
			ttsVoice: '',
			ttsSpeed: 1.0,
			sttEnabled: false,
			sttEngine: 'browser',
			volume: 80,
			audioDevice: '',
			inputDevice: '',
		},
	};
}
