#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
. "$(dirname -- "$0")/common.sh"

# Skip typecheck for now due to command issues
# pnpm typecheck || exit 1
pnpm lint || exit 1
pnpm test -w || exit 1
