name: Sign and Verify Workflow Artifacts

on:
  workflow_call:
    inputs:
      artifact-path:
        description: 'Path to artifact to sign'
        required: true
        type: string
      artifact-name:
        description: 'Name of the artifact'
        required: true
        type: string
    outputs:
      signature-url:
        description: 'URL to the signature in transparency log'
        value: ${{ jobs.sign.outputs.signature-url }}

permissions:
  id-token: write  # Required for OIDC authentication with Sigstore
  contents: read
  actions: read

jobs:
  sign:
    name: Sign Artifacts with Sigstore
    runs-on: ubuntu-latest
    outputs:
      signature-url: ${{ steps.sign.outputs.signature-url }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Download artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0
        with:
          cosign-release: 'v2.2.4'

      - name: Sign artifact with Sigstore
        id: sign
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          # Find all files to sign
          find "${{ inputs.artifact-path }}" -type f -name "*.tar.gz" -o -name "*.zip" -o -name "*.json" | while read -r file; do
            echo "Signing: $file"
            cosign sign-blob \
              --bundle "${file}.sigstore.json" \
              "$file"
          done

          # Output signature information
          echo "signature-url=https://search.sigstore.dev" >> $GITHUB_OUTPUT

      - name: Upload signed artifacts
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: ${{ inputs.artifact-name }}-signed
          path: ${{ inputs.artifact-path }}
          retention-days: 30

      - name: Verify signatures
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          # Verify all signatures created
          find "${{ inputs.artifact-path }}" -name "*.sigstore.json" | while read -r sig_file; do
            original_file="${sig_file%.sigstore.json}"
            echo "Verifying: $original_file"
            cosign verify-blob \
              --bundle "$sig_file" \
              "$original_file"
          done
