# Cloudflare Tunnel configuration for MCP service
# Explicitly binds service to fixed port 3024 (migrated off 3004 due to syspolicyd enforced termination)

ingress:
  - hostname: cortex-mcp.brainwav.io
    service: http://localhost:3024
  - service: http_status:404

# Optional: set to true for quick local dev; disable in production
no-autoupdate: true

metrics: 127.0.0.1:40713

tunnel: cortex-mcp
# Provide credentials via CLOUDFLARE_TUNNEL_TOKEN or cert.pem
